package com.advance.enumeration;

public enum UserAuthority {

	READ_PRODUCT, WRITE_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT, READ_ORDER, WRITE_ORDER, UPDATE_ORDER, DELETE_ORDER,
	READ_USER, UPDATE_USER, WRITE_USER, DELETE_USER, READ_COMPLAINT, WRITE_COMPLATE, UPDATE_COMPLAINT, DELETE_COMPLAINT;

}
